#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParsetCrawler.DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Parset")]
	public partial class EntityRelationsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertEntityRelations(EntityRelations instance);
    partial void UpdateEntityRelations(EntityRelations instance);
    partial void DeleteEntityRelations(EntityRelations instance);
    #endregion
		
		public EntityRelationsDataContext() : 
				base(global::ParsetCrawler.Properties.Settings.Default.ParsetConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public EntityRelationsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EntityRelationsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EntityRelationsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EntityRelationsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<vEntityRelations> vEntityRelations
		{
			get
			{
				return this.GetTable<vEntityRelations>();
			}
		}
		
		public System.Data.Linq.Table<EntityRelations> EntityRelations
		{
			get
			{
				return this.GetTable<EntityRelations>();
			}
		}
		
		public System.Data.Linq.Table<vRelatedArticles> vRelatedArticles
		{
			get
			{
				return this.GetTable<vRelatedArticles>();
			}
		}
		
		public System.Data.Linq.Table<vRelatedNews> vRelatedNews
		{
			get
			{
				return this.GetTable<vRelatedNews>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spGetRelatedEntities")]
		public ISingleResult<spGetRelatedEntitiesResult> spGetRelatedEntities([global::System.Data.Linq.Mapping.ParameterAttribute(Name="EntityCode", DbType="Int")] System.Nullable<int> entityCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HCEntityTypeCode", DbType="Int")] System.Nullable<int> hCEntityTypeCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HCRelatedEntityTypeCode", DbType="Int")] System.Nullable<int> hCRelatedEntityTypeCode)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), entityCode, hCEntityTypeCode, hCRelatedEntityTypeCode);
			return ((ISingleResult<spGetRelatedEntitiesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spSetRelatedEntities")]
		public int spSetRelatedEntities([global::System.Data.Linq.Mapping.ParameterAttribute(Name="EntityCode", DbType="Int")] System.Nullable<int> entityCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HCEntityTypeCode", DbType="Int")] System.Nullable<int> hCEntityTypeCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HCRelatedEntityTypeCode", DbType="Int")] System.Nullable<int> hCRelatedEntityTypeCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MatualCount", DbType="Int")] System.Nullable<int> matualCount)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), entityCode, hCEntityTypeCode, hCRelatedEntityTypeCode, matualCount);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vEntityRelations")]
	public partial class vEntityRelations
	{
		
		private int _Code;
		
		private System.Nullable<int> _EntityCode;
		
		private System.Nullable<int> _RelatedEntityCode;
		
		private string _Name;
		
		public vEntityRelations()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="Int NOT NULL")]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntityCode", DbType="Int")]
		public System.Nullable<int> EntityCode
		{
			get
			{
				return this._EntityCode;
			}
			set
			{
				if ((this._EntityCode != value))
				{
					this._EntityCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RelatedEntityCode", DbType="Int")]
		public System.Nullable<int> RelatedEntityCode
		{
			get
			{
				return this._RelatedEntityCode;
			}
			set
			{
				if ((this._RelatedEntityCode != value))
				{
					this._RelatedEntityCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(500)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EntityRelations")]
	public partial class EntityRelations : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Code;
		
		private int _EntityCode;
		
		private int _HCEntityTypeCode;
		
		private int _RelatedEntityCode;
		
		private System.Nullable<int> _HCRelatedEntityTypeCode;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodeChanging(int value);
    partial void OnCodeChanged();
    partial void OnEntityCodeChanging(int value);
    partial void OnEntityCodeChanged();
    partial void OnHCEntityTypeCodeChanging(int value);
    partial void OnHCEntityTypeCodeChanged();
    partial void OnRelatedEntityCodeChanging(int value);
    partial void OnRelatedEntityCodeChanged();
    partial void OnHCRelatedEntityTypeCodeChanging(System.Nullable<int> value);
    partial void OnHCRelatedEntityTypeCodeChanged();
    #endregion
		
		public EntityRelations()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntityCode", DbType="Int NOT NULL")]
		public int EntityCode
		{
			get
			{
				return this._EntityCode;
			}
			set
			{
				if ((this._EntityCode != value))
				{
					this.OnEntityCodeChanging(value);
					this.SendPropertyChanging();
					this._EntityCode = value;
					this.SendPropertyChanged("EntityCode");
					this.OnEntityCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCEntityTypeCode", DbType="Int NOT NULL")]
		public int HCEntityTypeCode
		{
			get
			{
				return this._HCEntityTypeCode;
			}
			set
			{
				if ((this._HCEntityTypeCode != value))
				{
					this.OnHCEntityTypeCodeChanging(value);
					this.SendPropertyChanging();
					this._HCEntityTypeCode = value;
					this.SendPropertyChanged("HCEntityTypeCode");
					this.OnHCEntityTypeCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RelatedEntityCode", DbType="Int NOT NULL")]
		public int RelatedEntityCode
		{
			get
			{
				return this._RelatedEntityCode;
			}
			set
			{
				if ((this._RelatedEntityCode != value))
				{
					this.OnRelatedEntityCodeChanging(value);
					this.SendPropertyChanging();
					this._RelatedEntityCode = value;
					this.SendPropertyChanged("RelatedEntityCode");
					this.OnRelatedEntityCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCRelatedEntityTypeCode", DbType="Int")]
		public System.Nullable<int> HCRelatedEntityTypeCode
		{
			get
			{
				return this._HCRelatedEntityTypeCode;
			}
			set
			{
				if ((this._HCRelatedEntityTypeCode != value))
				{
					this.OnHCRelatedEntityTypeCodeChanging(value);
					this.SendPropertyChanging();
					this._HCRelatedEntityTypeCode = value;
					this.SendPropertyChanged("HCRelatedEntityTypeCode");
					this.OnHCRelatedEntityTypeCodeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vRelatedArticles")]
	public partial class vRelatedArticles
	{
		
		private int _Code;
		
		private int _EntityCode;
		
		private int _HCEntityTypeCode;
		
		private int _RelatedCode;
		
		private string _Title;
		
		public vRelatedArticles()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="Int NOT NULL")]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntityCode", DbType="Int NOT NULL")]
		public int EntityCode
		{
			get
			{
				return this._EntityCode;
			}
			set
			{
				if ((this._EntityCode != value))
				{
					this._EntityCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCEntityTypeCode", DbType="Int NOT NULL")]
		public int HCEntityTypeCode
		{
			get
			{
				return this._HCEntityTypeCode;
			}
			set
			{
				if ((this._HCEntityTypeCode != value))
				{
					this._HCEntityTypeCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RelatedCode", DbType="Int NOT NULL")]
		public int RelatedCode
		{
			get
			{
				return this._RelatedCode;
			}
			set
			{
				if ((this._RelatedCode != value))
				{
					this._RelatedCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vRelatedNews")]
	public partial class vRelatedNews
	{
		
		private int _Code;
		
		private int _EntityCode;
		
		private string _Title;
		
		private int _HCEntityTypeCode;
		
		private int _RelatedCode;
		
		private string _ResourceName;
		
		private string _CatName;
		
		private string _PicName;
		
		private System.Nullable<System.DateTime> _NewsDate;
		
		private string _Contents;
		
		private System.Nullable<int> _ResourceSiteCode;
		
		public vRelatedNews()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="Int NOT NULL")]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntityCode", DbType="Int NOT NULL")]
		public int EntityCode
		{
			get
			{
				return this._EntityCode;
			}
			set
			{
				if ((this._EntityCode != value))
				{
					this._EntityCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(400) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCEntityTypeCode", DbType="Int NOT NULL")]
		public int HCEntityTypeCode
		{
			get
			{
				return this._HCEntityTypeCode;
			}
			set
			{
				if ((this._HCEntityTypeCode != value))
				{
					this._HCEntityTypeCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RelatedCode", DbType="Int NOT NULL")]
		public int RelatedCode
		{
			get
			{
				return this._RelatedCode;
			}
			set
			{
				if ((this._RelatedCode != value))
				{
					this._RelatedCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResourceName", DbType="NVarChar(500)")]
		public string ResourceName
		{
			get
			{
				return this._ResourceName;
			}
			set
			{
				if ((this._ResourceName != value))
				{
					this._ResourceName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CatName", DbType="NVarChar(500)")]
		public string CatName
		{
			get
			{
				return this._CatName;
			}
			set
			{
				if ((this._CatName != value))
				{
					this._CatName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PicName", DbType="NVarChar(200)")]
		public string PicName
		{
			get
			{
				return this._PicName;
			}
			set
			{
				if ((this._PicName != value))
				{
					this._PicName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewsDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> NewsDate
		{
			get
			{
				return this._NewsDate;
			}
			set
			{
				if ((this._NewsDate != value))
				{
					this._NewsDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contents", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Contents
		{
			get
			{
				return this._Contents;
			}
			set
			{
				if ((this._Contents != value))
				{
					this._Contents = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResourceSiteCode", DbType="Int")]
		public System.Nullable<int> ResourceSiteCode
		{
			get
			{
				return this._ResourceSiteCode;
			}
			set
			{
				if ((this._ResourceSiteCode != value))
				{
					this._ResourceSiteCode = value;
				}
			}
		}
	}
	
	public partial class spGetRelatedEntitiesResult
	{
		
		private int _EntityCode;
		
		private System.Nullable<int> _MatualCount;
		
		private System.Nullable<int> _HCEntityTypeCode;
		
		public spGetRelatedEntitiesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntityCode", DbType="Int NOT NULL")]
		public int EntityCode
		{
			get
			{
				return this._EntityCode;
			}
			set
			{
				if ((this._EntityCode != value))
				{
					this._EntityCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatualCount", DbType="Int")]
		public System.Nullable<int> MatualCount
		{
			get
			{
				return this._MatualCount;
			}
			set
			{
				if ((this._MatualCount != value))
				{
					this._MatualCount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCEntityTypeCode", DbType="Int")]
		public System.Nullable<int> HCEntityTypeCode
		{
			get
			{
				return this._HCEntityTypeCode;
			}
			set
			{
				if ((this._HCEntityTypeCode != value))
				{
					this._HCEntityTypeCode = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
