#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParsetCrawler.DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="parset")]
	public partial class NewsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertNewsNewsFlows(NewsNewsFlows instance);
    partial void UpdateNewsNewsFlows(NewsNewsFlows instance);
    partial void DeleteNewsNewsFlows(NewsNewsFlows instance);
    partial void InsertNewsFlowsKeywords(NewsFlowsKeywords instance);
    partial void UpdateNewsFlowsKeywords(NewsFlowsKeywords instance);
    partial void DeleteNewsFlowsKeywords(NewsFlowsKeywords instance);
    partial void InsertNews(News instance);
    partial void UpdateNews(News instance);
    partial void DeleteNews(News instance);
    partial void InsertNewsFlows(NewsFlows instance);
    partial void UpdateNewsFlows(NewsFlows instance);
    partial void DeleteNewsFlows(NewsFlows instance);
    partial void InsertNewsEmail(NewsEmail instance);
    partial void UpdateNewsEmail(NewsEmail instance);
    partial void DeleteNewsEmail(NewsEmail instance);
    partial void InsertEmailLists(EmailLists instance);
    partial void UpdateEmailLists(EmailLists instance);
    partial void DeleteEmailLists(EmailLists instance);
    partial void InsertEmailListSends(EmailListSends instance);
    partial void UpdateEmailListSends(EmailListSends instance);
    partial void DeleteEmailListSends(EmailListSends instance);
    partial void InsertNewsImages(NewsImages instance);
    partial void UpdateNewsImages(NewsImages instance);
    partial void DeleteNewsImages(NewsImages instance);
    #endregion
		
		public NewsDataContext() : 
				base(global::ParsetCrawler.Properties.Settings.Default.ParsetConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public NewsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NewsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NewsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NewsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<vNewsFlows> vNewsFlows
		{
			get
			{
				return this.GetTable<vNewsFlows>();
			}
		}
		
		public System.Data.Linq.Table<NewsNewsFlows> NewsNewsFlows
		{
			get
			{
				return this.GetTable<NewsNewsFlows>();
			}
		}
		
		public System.Data.Linq.Table<vNewsNewsFlows> vNewsNewsFlows
		{
			get
			{
				return this.GetTable<vNewsNewsFlows>();
			}
		}
		
		public System.Data.Linq.Table<NewsFlowsKeywords> NewsFlowsKeywords
		{
			get
			{
				return this.GetTable<NewsFlowsKeywords>();
			}
		}
		
		public System.Data.Linq.Table<vNewsFlowsKeywords> vNewsFlowsKeywords
		{
			get
			{
				return this.GetTable<vNewsFlowsKeywords>();
			}
		}
		
		public System.Data.Linq.Table<vTempNew> vTempNews
		{
			get
			{
				return this.GetTable<vTempNew>();
			}
		}
		
		public System.Data.Linq.Table<vTopNew> vTopNews
		{
			get
			{
				return this.GetTable<vTopNew>();
			}
		}
		
		public System.Data.Linq.Table<vNews> vNews
		{
			get
			{
				return this.GetTable<vNews>();
			}
		}
		
		public System.Data.Linq.Table<vImportantKeywords> vImportantKeywords
		{
			get
			{
				return this.GetTable<vImportantKeywords>();
			}
		}
		
		public System.Data.Linq.Table<News> News
		{
			get
			{
				return this.GetTable<News>();
			}
		}
		
		public System.Data.Linq.Table<NewsFlows> NewsFlows
		{
			get
			{
				return this.GetTable<NewsFlows>();
			}
		}
		
		public System.Data.Linq.Table<NewsflowNews> NewsflowNews
		{
			get
			{
				return this.GetTable<NewsflowNews>();
			}
		}
		
		public System.Data.Linq.Table<vKeywordsByTime> vKeywordsByTimes
		{
			get
			{
				return this.GetTable<vKeywordsByTime>();
			}
		}
		
		public System.Data.Linq.Table<vRandPicNews> vRandPicNews
		{
			get
			{
				return this.GetTable<vRandPicNews>();
			}
		}
		
		public System.Data.Linq.Table<vNewsflowNews> vNewsflowNews
		{
			get
			{
				return this.GetTable<vNewsflowNews>();
			}
		}
		
		public System.Data.Linq.Table<vNewsByCatCode> vNewsByCatCodes
		{
			get
			{
				return this.GetTable<vNewsByCatCode>();
			}
		}
		
		public System.Data.Linq.Table<vNewsByKeywords> vNewsByKeywords
		{
			get
			{
				return this.GetTable<vNewsByKeywords>();
			}
		}
		
		public System.Data.Linq.Table<vLatestNews> vLatestNews
		{
			get
			{
				return this.GetTable<vLatestNews>();
			}
		}
		
		public System.Data.Linq.Table<vLatestPicNews> vLatestPicNews
		{
			get
			{
				return this.GetTable<vLatestPicNews>();
			}
		}
		
		public System.Data.Linq.Table<NewsEmail> NewsEmails
		{
			get
			{
				return this.GetTable<NewsEmail>();
			}
		}
		
		public System.Data.Linq.Table<EmailLists> EmailLists
		{
			get
			{
				return this.GetTable<EmailLists>();
			}
		}
		
		public System.Data.Linq.Table<vNewsEmailItems> vNewsEmailItems
		{
			get
			{
				return this.GetTable<vNewsEmailItems>();
			}
		}
		
		public System.Data.Linq.Table<EmailListSends> EmailListSends
		{
			get
			{
				return this.GetTable<EmailListSends>();
			}
		}
		
		public System.Data.Linq.Table<NewsImages> NewsImages
		{
			get
			{
				return this.GetTable<NewsImages>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spGetRelatedNewsFlows")]
		public ISingleResult<spGetRelatedNewsFlowsResult> spGetRelatedNewsFlows([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NewsCode", DbType="Int")] System.Nullable<int> newsCode)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), newsCode);
			return ((ISingleResult<spGetRelatedNewsFlowsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spReportNewsStatistics")]
		public int spReportNewsStatistics([global::System.Data.Linq.Mapping.ParameterAttribute(Name="RepType", DbType="Int")] System.Nullable<int> repType, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StartNewsDate", DbType="DateTime")] System.Nullable<System.DateTime> startNewsDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EndNewsDate", DbType="DateTime")] System.Nullable<System.DateTime> endNewsDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Source", DbType="NVarChar(50)")] string source, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CountryCode", DbType="Int")] System.Nullable<int> countryCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LanguageCode", DbType="Int")] System.Nullable<int> languageCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HCResourceSiteCatCode", DbType="Int")] System.Nullable<int> hCResourceSiteCatCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HCLevelCode", DbType="Int")] System.Nullable<int> hCLevelCode)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), repType, startNewsDate, endNewsDate, source, countryCode, languageCode, hCResourceSiteCatCode, hCLevelCode);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spGetNewsflowKeywords")]
		public ISingleResult<spGetNewsflowKeywordsResult> spGetNewsflowKeywords([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NewsflowCode", DbType="Int")] System.Nullable<int> newsflowCode)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), newsflowCode);
			return ((ISingleResult<spGetNewsflowKeywordsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spSearchNews")]
		public ISingleResult<spSearchNewsResult> spSearchNews([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string keyword)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), keyword);
			return ((ISingleResult<spSearchNewsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spGetNotSentNewsEmails")]
		public ISingleResult<spGetNotSentNewsEmailsResult> spGetNotSentNewsEmails([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PersianDate", DbType="VarChar(10)")] string persianDate)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), persianDate);
			return ((ISingleResult<spGetNotSentNewsEmailsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spInsertNews")]
		public int spInsertNews([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ZoneCode", DbType="Int")] System.Nullable<int> zoneCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SiteCatCode", DbType="Int")] System.Nullable<int> siteCatCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HCResourceSiteCatCode", DbType="Int")] System.Nullable<int> hCResourceSiteCatCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Title", DbType="NVarChar(1000)")] string title, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Url", DbType="NVarChar(500)")] string url, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NewsDate", DbType="DateTime")] System.Nullable<System.DateTime> newsDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Contents", DbType="NText")] string contents, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ImgUrl", DbType="NVarChar(500)")] string imgUrl, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="VideoUrl", DbType="NVarChar(500)")] string videoUrl, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PicName", DbType="NVarChar(200)")] string picName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LanguageCode", DbType="Int")] System.Nullable<int> languageCode, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> imgWidth, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> imgHeight, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NewsCode", DbType="Int")] ref System.Nullable<int> newsCode)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), zoneCode, siteCatCode, hCResourceSiteCatCode, title, url, newsDate, contents, imgUrl, videoUrl, picName, languageCode, imgWidth, imgHeight, newsCode);
			newsCode = ((System.Nullable<int>)(result.GetParameterValue(13)));
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vNewsFlows")]
	public partial class vNewsFlows
	{
		
		private int _Code;
		
		private string _Title;
		
		private string _SDate;
		
		private string _EDate;
		
		public vNewsFlows()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(500)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDate", DbType="VarChar(10)")]
		public string SDate
		{
			get
			{
				return this._SDate;
			}
			set
			{
				if ((this._SDate != value))
				{
					this._SDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EDate", DbType="VarChar(10)")]
		public string EDate
		{
			get
			{
				return this._EDate;
			}
			set
			{
				if ((this._EDate != value))
				{
					this._EDate = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NewsNewsFlows")]
	public partial class NewsNewsFlows : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Code;
		
		private System.Nullable<int> _NewsCode;
		
		private System.Nullable<int> _NewsFlowCode;
		
		private EntityRef<News> _News;
		
		private EntityRef<NewsFlows> _NewsFlows;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodeChanging(int value);
    partial void OnCodeChanged();
    partial void OnNewsCodeChanging(System.Nullable<int> value);
    partial void OnNewsCodeChanged();
    partial void OnNewsFlowCodeChanging(System.Nullable<int> value);
    partial void OnNewsFlowCodeChanged();
    #endregion
		
		public NewsNewsFlows()
		{
			this._News = default(EntityRef<News>);
			this._NewsFlows = default(EntityRef<NewsFlows>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewsCode", DbType="Int")]
		public System.Nullable<int> NewsCode
		{
			get
			{
				return this._NewsCode;
			}
			set
			{
				if ((this._NewsCode != value))
				{
					if (this._News.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNewsCodeChanging(value);
					this.SendPropertyChanging();
					this._NewsCode = value;
					this.SendPropertyChanged("NewsCode");
					this.OnNewsCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewsFlowCode", DbType="Int")]
		public System.Nullable<int> NewsFlowCode
		{
			get
			{
				return this._NewsFlowCode;
			}
			set
			{
				if ((this._NewsFlowCode != value))
				{
					if (this._NewsFlows.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNewsFlowCodeChanging(value);
					this.SendPropertyChanging();
					this._NewsFlowCode = value;
					this.SendPropertyChanged("NewsFlowCode");
					this.OnNewsFlowCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="News_NewsNewsFlows", Storage="_News", ThisKey="NewsCode", OtherKey="Code", IsForeignKey=true, DeleteRule="CASCADE")]
		public News News
		{
			get
			{
				return this._News.Entity;
			}
			set
			{
				News previousValue = this._News.Entity;
				if (((previousValue != value) 
							|| (this._News.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._News.Entity = null;
						previousValue.NewsNewsFlows.Remove(this);
					}
					this._News.Entity = value;
					if ((value != null))
					{
						value.NewsNewsFlows.Add(this);
						this._NewsCode = value.Code;
					}
					else
					{
						this._NewsCode = default(Nullable<int>);
					}
					this.SendPropertyChanged("News");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NewsFlows_NewsNewsFlows", Storage="_NewsFlows", ThisKey="NewsFlowCode", OtherKey="Code", IsForeignKey=true)]
		public NewsFlows NewsFlows
		{
			get
			{
				return this._NewsFlows.Entity;
			}
			set
			{
				NewsFlows previousValue = this._NewsFlows.Entity;
				if (((previousValue != value) 
							|| (this._NewsFlows.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NewsFlows.Entity = null;
						previousValue.NewsNewsFlows.Remove(this);
					}
					this._NewsFlows.Entity = value;
					if ((value != null))
					{
						value.NewsNewsFlows.Add(this);
						this._NewsFlowCode = value.Code;
					}
					else
					{
						this._NewsFlowCode = default(Nullable<int>);
					}
					this.SendPropertyChanged("NewsFlows");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vNewsNewsFlows")]
	public partial class vNewsNewsFlows
	{
		
		private int _Code;
		
		private System.Nullable<int> _NewsCode;
		
		private string _Title;
		
		public vNewsNewsFlows()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="Int NOT NULL")]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewsCode", DbType="Int")]
		public System.Nullable<int> NewsCode
		{
			get
			{
				return this._NewsCode;
			}
			set
			{
				if ((this._NewsCode != value))
				{
					this._NewsCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(500)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NewsFlowsKeywords")]
	public partial class NewsFlowsKeywords : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Code;
		
		private System.Nullable<int> _NewsFlowCode;
		
		private System.Nullable<int> _KeywordCode;
		
		private EntityRef<NewsFlows> _NewsFlows;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodeChanging(int value);
    partial void OnCodeChanged();
    partial void OnNewsFlowCodeChanging(System.Nullable<int> value);
    partial void OnNewsFlowCodeChanged();
    partial void OnKeywordCodeChanging(System.Nullable<int> value);
    partial void OnKeywordCodeChanged();
    #endregion
		
		public NewsFlowsKeywords()
		{
			this._NewsFlows = default(EntityRef<NewsFlows>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewsFlowCode", DbType="Int")]
		public System.Nullable<int> NewsFlowCode
		{
			get
			{
				return this._NewsFlowCode;
			}
			set
			{
				if ((this._NewsFlowCode != value))
				{
					if (this._NewsFlows.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNewsFlowCodeChanging(value);
					this.SendPropertyChanging();
					this._NewsFlowCode = value;
					this.SendPropertyChanged("NewsFlowCode");
					this.OnNewsFlowCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeywordCode", DbType="Int")]
		public System.Nullable<int> KeywordCode
		{
			get
			{
				return this._KeywordCode;
			}
			set
			{
				if ((this._KeywordCode != value))
				{
					this.OnKeywordCodeChanging(value);
					this.SendPropertyChanging();
					this._KeywordCode = value;
					this.SendPropertyChanged("KeywordCode");
					this.OnKeywordCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NewsFlows_NewsFlowsKeywords", Storage="_NewsFlows", ThisKey="NewsFlowCode", OtherKey="Code", IsForeignKey=true)]
		public NewsFlows NewsFlows
		{
			get
			{
				return this._NewsFlows.Entity;
			}
			set
			{
				NewsFlows previousValue = this._NewsFlows.Entity;
				if (((previousValue != value) 
							|| (this._NewsFlows.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NewsFlows.Entity = null;
						previousValue.NewsFlowsKeywords.Remove(this);
					}
					this._NewsFlows.Entity = value;
					if ((value != null))
					{
						value.NewsFlowsKeywords.Add(this);
						this._NewsFlowCode = value.Code;
					}
					else
					{
						this._NewsFlowCode = default(Nullable<int>);
					}
					this.SendPropertyChanged("NewsFlows");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vNewsFlowsKeywords")]
	public partial class vNewsFlowsKeywords
	{
		
		private int _Code;
		
		private System.Nullable<int> _NewsFlowCode;
		
		private string _Name;
		
		public vNewsFlowsKeywords()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="Int NOT NULL")]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewsFlowCode", DbType="Int")]
		public System.Nullable<int> NewsFlowCode
		{
			get
			{
				return this._NewsFlowCode;
			}
			set
			{
				if ((this._NewsFlowCode != value))
				{
					this._NewsFlowCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(100)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vTempNews")]
	public partial class vTempNew
	{
		
		private int _Code;
		
		private string _Contents;
		
		public vTempNew()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contents", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Contents
		{
			get
			{
				return this._Contents;
			}
			set
			{
				if ((this._Contents != value))
				{
					this._Contents = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vTopNews")]
	public partial class vTopNew
	{
		
		private string _Contents;
		
		private int _Code;
		
		private string _Title;
		
		private System.Nullable<int> _RelatedNewsCount;
		
		private System.Nullable<System.DateTime> _NewsDate;
		
		private string _PicName;
		
		private System.Nullable<int> _LanguageCode;
		
		public vTopNew()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contents", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Contents
		{
			get
			{
				return this._Contents;
			}
			set
			{
				if ((this._Contents != value))
				{
					this._Contents = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="Int NOT NULL")]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(400) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RelatedNewsCount", DbType="Int")]
		public System.Nullable<int> RelatedNewsCount
		{
			get
			{
				return this._RelatedNewsCount;
			}
			set
			{
				if ((this._RelatedNewsCount != value))
				{
					this._RelatedNewsCount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewsDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> NewsDate
		{
			get
			{
				return this._NewsDate;
			}
			set
			{
				if ((this._NewsDate != value))
				{
					this._NewsDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PicName", DbType="NVarChar(200)")]
		public string PicName
		{
			get
			{
				return this._PicName;
			}
			set
			{
				if ((this._PicName != value))
				{
					this._PicName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LanguageCode", DbType="Int")]
		public System.Nullable<int> LanguageCode
		{
			get
			{
				return this._LanguageCode;
			}
			set
			{
				if ((this._LanguageCode != value))
				{
					this._LanguageCode = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vNews")]
	public partial class vNews
	{
		
		private int _Code;
		
		private string _Title;
		
		private string _NewsDate;
		
		private string _CatName;
		
		private string _Priority;
		
		private string _GatherType;
		
		private string _Language;
		
		private System.Nullable<bool> _Active;
		
		private System.Nullable<int> _HCResourceSiteCatCode;
		
		private System.Nullable<System.DateTime> _NewsDate2;
		
		private System.Nullable<int> _Rate;
		
		private System.Nullable<int> _HCLevelCode;
		
		public vNews()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="Int NOT NULL")]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(400) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewsDate", DbType="VarChar(10)")]
		public string NewsDate
		{
			get
			{
				return this._NewsDate;
			}
			set
			{
				if ((this._NewsDate != value))
				{
					this._NewsDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CatName", DbType="NVarChar(500)")]
		public string CatName
		{
			get
			{
				return this._CatName;
			}
			set
			{
				if ((this._CatName != value))
				{
					this._CatName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Priority", DbType="NVarChar(500)")]
		public string Priority
		{
			get
			{
				return this._Priority;
			}
			set
			{
				if ((this._Priority != value))
				{
					this._Priority = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GatherType", DbType="NVarChar(500)")]
		public string GatherType
		{
			get
			{
				return this._GatherType;
			}
			set
			{
				if ((this._GatherType != value))
				{
					this._GatherType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Language", DbType="NVarChar(500)")]
		public string Language
		{
			get
			{
				return this._Language;
			}
			set
			{
				if ((this._Language != value))
				{
					this._Language = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit")]
		public System.Nullable<bool> Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this._Active = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCResourceSiteCatCode", DbType="Int")]
		public System.Nullable<int> HCResourceSiteCatCode
		{
			get
			{
				return this._HCResourceSiteCatCode;
			}
			set
			{
				if ((this._HCResourceSiteCatCode != value))
				{
					this._HCResourceSiteCatCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewsDate2", DbType="DateTime")]
		public System.Nullable<System.DateTime> NewsDate2
		{
			get
			{
				return this._NewsDate2;
			}
			set
			{
				if ((this._NewsDate2 != value))
				{
					this._NewsDate2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rate", DbType="Int")]
		public System.Nullable<int> Rate
		{
			get
			{
				return this._Rate;
			}
			set
			{
				if ((this._Rate != value))
				{
					this._Rate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCLevelCode", DbType="Int")]
		public System.Nullable<int> HCLevelCode
		{
			get
			{
				return this._HCLevelCode;
			}
			set
			{
				if ((this._HCLevelCode != value))
				{
					this._HCLevelCode = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vImportantKeywords")]
	public partial class vImportantKeywords
	{
		
		private string _Keyword;
		
		private System.Nullable<int> _KeywordCount;
		
		private int _KeywordCode;
		
		public vImportantKeywords()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Keyword", DbType="NVarChar(100)")]
		public string Keyword
		{
			get
			{
				return this._Keyword;
			}
			set
			{
				if ((this._Keyword != value))
				{
					this._Keyword = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeywordCount", DbType="Int")]
		public System.Nullable<int> KeywordCount
		{
			get
			{
				return this._KeywordCount;
			}
			set
			{
				if ((this._KeywordCount != value))
				{
					this._KeywordCount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeywordCode", DbType="Int NOT NULL")]
		public int KeywordCode
		{
			get
			{
				return this._KeywordCode;
			}
			set
			{
				if ((this._KeywordCode != value))
				{
					this._KeywordCode = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.News")]
	public partial class News : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Code;
		
		private string _Title;
		
		private System.Nullable<int> _HCResourceSiteCatCode;
		
		private System.Nullable<int> _HCPriorityCode;
		
		private System.Nullable<System.DateTime> _NewsDate;
		
		private string _Source;
		
		private System.Nullable<bool> _Urgent;
		
		private string _FileName;
		
		private string _PicName;
		
		private string _Contents;
		
		private string _Url;
		
		private string _ImgUrl;
		
		private System.Nullable<int> _HCLevelCode;
		
		private System.Nullable<int> _ResouceSiteCatCode;
		
		private System.Nullable<bool> _Active;
		
		private System.Nullable<int> _HCGatherTypeCode;
		
		private System.Nullable<int> _Rate;
		
		private System.Nullable<bool> _ShowInFirstPage;
		
		private System.Nullable<int> _LanguageCode;
		
		private string _ConvertedContent;
		
		private System.Nullable<int> _ViewCount;
		
		private System.Nullable<int> _ZoneCode;
		
		private System.Nullable<System.DateTime> _CreateTime;
		
		private System.Nullable<System.DateTime> _UpdateTime;
		
		private EntitySet<NewsNewsFlows> _NewsNewsFlows;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodeChanging(int value);
    partial void OnCodeChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnHCResourceSiteCatCodeChanging(System.Nullable<int> value);
    partial void OnHCResourceSiteCatCodeChanged();
    partial void OnHCPriorityCodeChanging(System.Nullable<int> value);
    partial void OnHCPriorityCodeChanged();
    partial void OnNewsDateChanging(System.Nullable<System.DateTime> value);
    partial void OnNewsDateChanged();
    partial void OnSourceChanging(string value);
    partial void OnSourceChanged();
    partial void OnUrgentChanging(System.Nullable<bool> value);
    partial void OnUrgentChanged();
    partial void OnFileNameChanging(string value);
    partial void OnFileNameChanged();
    partial void OnPicNameChanging(string value);
    partial void OnPicNameChanged();
    partial void OnContentsChanging(string value);
    partial void OnContentsChanged();
    partial void OnUrlChanging(string value);
    partial void OnUrlChanged();
    partial void OnImgUrlChanging(string value);
    partial void OnImgUrlChanged();
    partial void OnHCLevelCodeChanging(System.Nullable<int> value);
    partial void OnHCLevelCodeChanged();
    partial void OnResouceSiteCatCodeChanging(System.Nullable<int> value);
    partial void OnResouceSiteCatCodeChanged();
    partial void OnActiveChanging(System.Nullable<bool> value);
    partial void OnActiveChanged();
    partial void OnHCGatherTypeCodeChanging(System.Nullable<int> value);
    partial void OnHCGatherTypeCodeChanged();
    partial void OnRateChanging(System.Nullable<int> value);
    partial void OnRateChanged();
    partial void OnShowInFirstPageChanging(System.Nullable<bool> value);
    partial void OnShowInFirstPageChanged();
    partial void OnLanguageCodeChanging(System.Nullable<int> value);
    partial void OnLanguageCodeChanged();
    partial void OnConvertedContentChanging(string value);
    partial void OnConvertedContentChanged();
    partial void OnViewCountChanging(System.Nullable<int> value);
    partial void OnViewCountChanged();
    partial void OnZoneCodeChanging(System.Nullable<int> value);
    partial void OnZoneCodeChanged();
    partial void OnCreateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateTimeChanged();
    partial void OnUpdateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdateTimeChanged();
    #endregion
		
		public News()
		{
			this._NewsNewsFlows = new EntitySet<NewsNewsFlows>(new Action<NewsNewsFlows>(this.attach_NewsNewsFlows), new Action<NewsNewsFlows>(this.detach_NewsNewsFlows));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(400) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCResourceSiteCatCode", DbType="Int")]
		public System.Nullable<int> HCResourceSiteCatCode
		{
			get
			{
				return this._HCResourceSiteCatCode;
			}
			set
			{
				if ((this._HCResourceSiteCatCode != value))
				{
					this.OnHCResourceSiteCatCodeChanging(value);
					this.SendPropertyChanging();
					this._HCResourceSiteCatCode = value;
					this.SendPropertyChanged("HCResourceSiteCatCode");
					this.OnHCResourceSiteCatCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCPriorityCode", DbType="Int")]
		public System.Nullable<int> HCPriorityCode
		{
			get
			{
				return this._HCPriorityCode;
			}
			set
			{
				if ((this._HCPriorityCode != value))
				{
					this.OnHCPriorityCodeChanging(value);
					this.SendPropertyChanging();
					this._HCPriorityCode = value;
					this.SendPropertyChanged("HCPriorityCode");
					this.OnHCPriorityCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewsDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> NewsDate
		{
			get
			{
				return this._NewsDate;
			}
			set
			{
				if ((this._NewsDate != value))
				{
					this.OnNewsDateChanging(value);
					this.SendPropertyChanging();
					this._NewsDate = value;
					this.SendPropertyChanged("NewsDate");
					this.OnNewsDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Source", DbType="NVarChar(100)")]
		public string Source
		{
			get
			{
				return this._Source;
			}
			set
			{
				if ((this._Source != value))
				{
					this.OnSourceChanging(value);
					this.SendPropertyChanging();
					this._Source = value;
					this.SendPropertyChanged("Source");
					this.OnSourceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Urgent", DbType="Bit")]
		public System.Nullable<bool> Urgent
		{
			get
			{
				return this._Urgent;
			}
			set
			{
				if ((this._Urgent != value))
				{
					this.OnUrgentChanging(value);
					this.SendPropertyChanging();
					this._Urgent = value;
					this.SendPropertyChanged("Urgent");
					this.OnUrgentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileName", DbType="NVarChar(200)")]
		public string FileName
		{
			get
			{
				return this._FileName;
			}
			set
			{
				if ((this._FileName != value))
				{
					this.OnFileNameChanging(value);
					this.SendPropertyChanging();
					this._FileName = value;
					this.SendPropertyChanged("FileName");
					this.OnFileNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PicName", DbType="NVarChar(200)")]
		public string PicName
		{
			get
			{
				return this._PicName;
			}
			set
			{
				if ((this._PicName != value))
				{
					this.OnPicNameChanging(value);
					this.SendPropertyChanging();
					this._PicName = value;
					this.SendPropertyChanged("PicName");
					this.OnPicNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contents", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Contents
		{
			get
			{
				return this._Contents;
			}
			set
			{
				if ((this._Contents != value))
				{
					this.OnContentsChanging(value);
					this.SendPropertyChanging();
					this._Contents = value;
					this.SendPropertyChanged("Contents");
					this.OnContentsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Url", DbType="nVarChar(500)")]
		public string Url
		{
			get
			{
				return this._Url;
			}
			set
			{
				if ((this._Url != value))
				{
					this.OnUrlChanging(value);
					this.SendPropertyChanging();
					this._Url = value;
					this.SendPropertyChanged("Url");
					this.OnUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImgUrl", DbType="VarChar(500)")]
		public string ImgUrl
		{
			get
			{
				return this._ImgUrl;
			}
			set
			{
				if ((this._ImgUrl != value))
				{
					this.OnImgUrlChanging(value);
					this.SendPropertyChanging();
					this._ImgUrl = value;
					this.SendPropertyChanged("ImgUrl");
					this.OnImgUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCLevelCode", DbType="Int")]
		public System.Nullable<int> HCLevelCode
		{
			get
			{
				return this._HCLevelCode;
			}
			set
			{
				if ((this._HCLevelCode != value))
				{
					this.OnHCLevelCodeChanging(value);
					this.SendPropertyChanging();
					this._HCLevelCode = value;
					this.SendPropertyChanged("HCLevelCode");
					this.OnHCLevelCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResouceSiteCatCode", DbType="Int")]
		public System.Nullable<int> ResouceSiteCatCode
		{
			get
			{
				return this._ResouceSiteCatCode;
			}
			set
			{
				if ((this._ResouceSiteCatCode != value))
				{
					this.OnResouceSiteCatCodeChanging(value);
					this.SendPropertyChanging();
					this._ResouceSiteCatCode = value;
					this.SendPropertyChanged("ResouceSiteCatCode");
					this.OnResouceSiteCatCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit")]
		public System.Nullable<bool> Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this.OnActiveChanging(value);
					this.SendPropertyChanging();
					this._Active = value;
					this.SendPropertyChanged("Active");
					this.OnActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCGatherTypeCode", DbType="Int")]
		public System.Nullable<int> HCGatherTypeCode
		{
			get
			{
				return this._HCGatherTypeCode;
			}
			set
			{
				if ((this._HCGatherTypeCode != value))
				{
					this.OnHCGatherTypeCodeChanging(value);
					this.SendPropertyChanging();
					this._HCGatherTypeCode = value;
					this.SendPropertyChanged("HCGatherTypeCode");
					this.OnHCGatherTypeCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rate", DbType="Int")]
		public System.Nullable<int> Rate
		{
			get
			{
				return this._Rate;
			}
			set
			{
				if ((this._Rate != value))
				{
					this.OnRateChanging(value);
					this.SendPropertyChanging();
					this._Rate = value;
					this.SendPropertyChanged("Rate");
					this.OnRateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShowInFirstPage", DbType="Bit")]
		public System.Nullable<bool> ShowInFirstPage
		{
			get
			{
				return this._ShowInFirstPage;
			}
			set
			{
				if ((this._ShowInFirstPage != value))
				{
					this.OnShowInFirstPageChanging(value);
					this.SendPropertyChanging();
					this._ShowInFirstPage = value;
					this.SendPropertyChanged("ShowInFirstPage");
					this.OnShowInFirstPageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LanguageCode", DbType="Int")]
		public System.Nullable<int> LanguageCode
		{
			get
			{
				return this._LanguageCode;
			}
			set
			{
				if ((this._LanguageCode != value))
				{
					this.OnLanguageCodeChanging(value);
					this.SendPropertyChanging();
					this._LanguageCode = value;
					this.SendPropertyChanged("LanguageCode");
					this.OnLanguageCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConvertedContent", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string ConvertedContent
		{
			get
			{
				return this._ConvertedContent;
			}
			set
			{
				if ((this._ConvertedContent != value))
				{
					this.OnConvertedContentChanging(value);
					this.SendPropertyChanging();
					this._ConvertedContent = value;
					this.SendPropertyChanged("ConvertedContent");
					this.OnConvertedContentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ViewCount", DbType="Int")]
		public System.Nullable<int> ViewCount
		{
			get
			{
				return this._ViewCount;
			}
			set
			{
				if ((this._ViewCount != value))
				{
					this.OnViewCountChanging(value);
					this.SendPropertyChanging();
					this._ViewCount = value;
					this.SendPropertyChanged("ViewCount");
					this.OnViewCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZoneCode", DbType="Int")]
		public System.Nullable<int> ZoneCode
		{
			get
			{
				return this._ZoneCode;
			}
			set
			{
				if ((this._ZoneCode != value))
				{
					this.OnZoneCodeChanging(value);
					this.SendPropertyChanging();
					this._ZoneCode = value;
					this.SendPropertyChanged("ZoneCode");
					this.OnZoneCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateTime
		{
			get
			{
				return this._CreateTime;
			}
			set
			{
				if ((this._CreateTime != value))
				{
					this.OnCreateTimeChanging(value);
					this.SendPropertyChanging();
					this._CreateTime = value;
					this.SendPropertyChanged("CreateTime");
					this.OnCreateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdateTime
		{
			get
			{
				return this._UpdateTime;
			}
			set
			{
				if ((this._UpdateTime != value))
				{
					this.OnUpdateTimeChanging(value);
					this.SendPropertyChanging();
					this._UpdateTime = value;
					this.SendPropertyChanged("UpdateTime");
					this.OnUpdateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="News_NewsNewsFlows", Storage="_NewsNewsFlows", ThisKey="Code", OtherKey="NewsCode")]
		public EntitySet<NewsNewsFlows> NewsNewsFlows
		{
			get
			{
				return this._NewsNewsFlows;
			}
			set
			{
				this._NewsNewsFlows.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NewsNewsFlows(NewsNewsFlows entity)
		{
			this.SendPropertyChanging();
			entity.News = this;
		}
		
		private void detach_NewsNewsFlows(NewsNewsFlows entity)
		{
			this.SendPropertyChanging();
			entity.News = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NewsFlows")]
	public partial class NewsFlows : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Code;
		
		private string _Title;
		
		private System.Nullable<System.DateTime> _StartDate;
		
		private System.Nullable<System.DateTime> _EndDate;
		
		private string _PicName;
		
		private System.Nullable<int> _ShowOrder;
		
		private EntitySet<NewsNewsFlows> _NewsNewsFlows;
		
		private EntitySet<NewsFlowsKeywords> _NewsFlowsKeywords;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodeChanging(int value);
    partial void OnCodeChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnStartDateChanging(System.Nullable<System.DateTime> value);
    partial void OnStartDateChanged();
    partial void OnEndDateChanging(System.Nullable<System.DateTime> value);
    partial void OnEndDateChanged();
    partial void OnPicNameChanging(string value);
    partial void OnPicNameChanged();
    partial void OnShowOrderChanging(System.Nullable<int> value);
    partial void OnShowOrderChanged();
    #endregion
		
		public NewsFlows()
		{
			this._NewsNewsFlows = new EntitySet<NewsNewsFlows>(new Action<NewsNewsFlows>(this.attach_NewsNewsFlows), new Action<NewsNewsFlows>(this.detach_NewsNewsFlows));
			this._NewsFlowsKeywords = new EntitySet<NewsFlowsKeywords>(new Action<NewsFlowsKeywords>(this.attach_NewsFlowsKeywords), new Action<NewsFlowsKeywords>(this.detach_NewsFlowsKeywords));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(500)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> StartDate
		{
			get
			{
				return this._StartDate;
			}
			set
			{
				if ((this._StartDate != value))
				{
					this.OnStartDateChanging(value);
					this.SendPropertyChanging();
					this._StartDate = value;
					this.SendPropertyChanged("StartDate");
					this.OnStartDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> EndDate
		{
			get
			{
				return this._EndDate;
			}
			set
			{
				if ((this._EndDate != value))
				{
					this.OnEndDateChanging(value);
					this.SendPropertyChanging();
					this._EndDate = value;
					this.SendPropertyChanged("EndDate");
					this.OnEndDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PicName", DbType="NVarChar(200)")]
		public string PicName
		{
			get
			{
				return this._PicName;
			}
			set
			{
				if ((this._PicName != value))
				{
					this.OnPicNameChanging(value);
					this.SendPropertyChanging();
					this._PicName = value;
					this.SendPropertyChanged("PicName");
					this.OnPicNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShowOrder", DbType="Int")]
		public System.Nullable<int> ShowOrder
		{
			get
			{
				return this._ShowOrder;
			}
			set
			{
				if ((this._ShowOrder != value))
				{
					this.OnShowOrderChanging(value);
					this.SendPropertyChanging();
					this._ShowOrder = value;
					this.SendPropertyChanged("ShowOrder");
					this.OnShowOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NewsFlows_NewsNewsFlows", Storage="_NewsNewsFlows", ThisKey="Code", OtherKey="NewsFlowCode")]
		public EntitySet<NewsNewsFlows> NewsNewsFlows
		{
			get
			{
				return this._NewsNewsFlows;
			}
			set
			{
				this._NewsNewsFlows.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NewsFlows_NewsFlowsKeywords", Storage="_NewsFlowsKeywords", ThisKey="Code", OtherKey="NewsFlowCode")]
		public EntitySet<NewsFlowsKeywords> NewsFlowsKeywords
		{
			get
			{
				return this._NewsFlowsKeywords;
			}
			set
			{
				this._NewsFlowsKeywords.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NewsNewsFlows(NewsNewsFlows entity)
		{
			this.SendPropertyChanging();
			entity.NewsFlows = this;
		}
		
		private void detach_NewsNewsFlows(NewsNewsFlows entity)
		{
			this.SendPropertyChanging();
			entity.NewsFlows = null;
		}
		
		private void attach_NewsFlowsKeywords(NewsFlowsKeywords entity)
		{
			this.SendPropertyChanging();
			entity.NewsFlows = this;
		}
		
		private void detach_NewsFlowsKeywords(NewsFlowsKeywords entity)
		{
			this.SendPropertyChanging();
			entity.NewsFlows = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vNewsflowNews")]
	public partial class NewsflowNews
	{
		
		private int _Code;
		
		private System.Nullable<int> _NewsFlowCode;
		
		private string _Title;
		
		private string _Contents;
		
		private System.Nullable<System.DateTime> _NewsDate;
		
		private string _PicName;
		
		private string _ResourceName;
		
		public NewsflowNews()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="Int NOT NULL")]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewsFlowCode", DbType="Int")]
		public System.Nullable<int> NewsFlowCode
		{
			get
			{
				return this._NewsFlowCode;
			}
			set
			{
				if ((this._NewsFlowCode != value))
				{
					this._NewsFlowCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(400) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contents", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Contents
		{
			get
			{
				return this._Contents;
			}
			set
			{
				if ((this._Contents != value))
				{
					this._Contents = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewsDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> NewsDate
		{
			get
			{
				return this._NewsDate;
			}
			set
			{
				if ((this._NewsDate != value))
				{
					this._NewsDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PicName", DbType="NVarChar(200)")]
		public string PicName
		{
			get
			{
				return this._PicName;
			}
			set
			{
				if ((this._PicName != value))
				{
					this._PicName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResourceName", DbType="NVarChar(500)")]
		public string ResourceName
		{
			get
			{
				return this._ResourceName;
			}
			set
			{
				if ((this._ResourceName != value))
				{
					this._ResourceName = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vKeywordsByTime")]
	public partial class vKeywordsByTime
	{
		
		private System.Nullable<int> _NewsCount;
		
		private string _Keyword;
		
		private string _NewsDay;
		
		public vKeywordsByTime()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewsCount", DbType="Int")]
		public System.Nullable<int> NewsCount
		{
			get
			{
				return this._NewsCount;
			}
			set
			{
				if ((this._NewsCount != value))
				{
					this._NewsCount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Keyword", DbType="NVarChar(100)")]
		public string Keyword
		{
			get
			{
				return this._Keyword;
			}
			set
			{
				if ((this._Keyword != value))
				{
					this._Keyword = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewsDay", DbType="VarChar(10)")]
		public string NewsDay
		{
			get
			{
				return this._NewsDay;
			}
			set
			{
				if ((this._NewsDay != value))
				{
					this._NewsDay = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vRandPicNews")]
	public partial class vRandPicNews
	{
		
		private int _Code;
		
		private string _Title;
		
		private string _ResourceName;
		
		private string _PicName;
		
		private string _Contents;
		
		private System.Nullable<System.DateTime> _NewsDate;
		
		private int _ResourceSiteCode;
		
		private int _ResourceSiteCatCode;
		
		public vRandPicNews()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="Int NOT NULL")]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(400) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResourceName", DbType="NVarChar(500)")]
		public string ResourceName
		{
			get
			{
				return this._ResourceName;
			}
			set
			{
				if ((this._ResourceName != value))
				{
					this._ResourceName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PicName", DbType="NVarChar(200)")]
		public string PicName
		{
			get
			{
				return this._PicName;
			}
			set
			{
				if ((this._PicName != value))
				{
					this._PicName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contents", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Contents
		{
			get
			{
				return this._Contents;
			}
			set
			{
				if ((this._Contents != value))
				{
					this._Contents = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewsDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> NewsDate
		{
			get
			{
				return this._NewsDate;
			}
			set
			{
				if ((this._NewsDate != value))
				{
					this._NewsDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResourceSiteCode", DbType="Int NOT NULL")]
		public int ResourceSiteCode
		{
			get
			{
				return this._ResourceSiteCode;
			}
			set
			{
				if ((this._ResourceSiteCode != value))
				{
					this._ResourceSiteCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResourceSiteCatCode", DbType="Int NOT NULL")]
		public int ResourceSiteCatCode
		{
			get
			{
				return this._ResourceSiteCatCode;
			}
			set
			{
				if ((this._ResourceSiteCatCode != value))
				{
					this._ResourceSiteCatCode = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vNewsflowNews")]
	public partial class vNewsflowNews
	{
		
		private int _Code;
		
		private System.Nullable<int> _NewsFlowCode;
		
		private string _Title;
		
		private string _Contents;
		
		private System.Nullable<System.DateTime> _NewsDate;
		
		private string _PicName;
		
		private string _ResourceName;
		
		private int _ResourceSiteCode;
		
		public vNewsflowNews()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="Int NOT NULL")]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewsFlowCode", DbType="Int")]
		public System.Nullable<int> NewsFlowCode
		{
			get
			{
				return this._NewsFlowCode;
			}
			set
			{
				if ((this._NewsFlowCode != value))
				{
					this._NewsFlowCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(400) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contents", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Contents
		{
			get
			{
				return this._Contents;
			}
			set
			{
				if ((this._Contents != value))
				{
					this._Contents = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewsDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> NewsDate
		{
			get
			{
				return this._NewsDate;
			}
			set
			{
				if ((this._NewsDate != value))
				{
					this._NewsDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PicName", DbType="NVarChar(200)")]
		public string PicName
		{
			get
			{
				return this._PicName;
			}
			set
			{
				if ((this._PicName != value))
				{
					this._PicName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResourceName", DbType="NVarChar(500)")]
		public string ResourceName
		{
			get
			{
				return this._ResourceName;
			}
			set
			{
				if ((this._ResourceName != value))
				{
					this._ResourceName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResourceSiteCode", DbType="Int NOT NULL")]
		public int ResourceSiteCode
		{
			get
			{
				return this._ResourceSiteCode;
			}
			set
			{
				if ((this._ResourceSiteCode != value))
				{
					this._ResourceSiteCode = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vNewsByCatCode")]
	public partial class vNewsByCatCode
	{
		
		private int _Code;
		
		private string _Title;
		
		private string _PicName;
		
		private string _Contents;
		
		private System.Nullable<int> _CatCode;
		
		private string _ResourceName;
		
		private System.Nullable<System.DateTime> _NewsDate;
		
		private int _ResourceSiteCode;
		
		public vNewsByCatCode()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="Int NOT NULL")]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(400) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PicName", DbType="NVarChar(200)")]
		public string PicName
		{
			get
			{
				return this._PicName;
			}
			set
			{
				if ((this._PicName != value))
				{
					this._PicName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contents", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Contents
		{
			get
			{
				return this._Contents;
			}
			set
			{
				if ((this._Contents != value))
				{
					this._Contents = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CatCode", DbType="Int")]
		public System.Nullable<int> CatCode
		{
			get
			{
				return this._CatCode;
			}
			set
			{
				if ((this._CatCode != value))
				{
					this._CatCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResourceName", DbType="NVarChar(500)")]
		public string ResourceName
		{
			get
			{
				return this._ResourceName;
			}
			set
			{
				if ((this._ResourceName != value))
				{
					this._ResourceName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewsDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> NewsDate
		{
			get
			{
				return this._NewsDate;
			}
			set
			{
				if ((this._NewsDate != value))
				{
					this._NewsDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResourceSiteCode", DbType="Int NOT NULL")]
		public int ResourceSiteCode
		{
			get
			{
				return this._ResourceSiteCode;
			}
			set
			{
				if ((this._ResourceSiteCode != value))
				{
					this._ResourceSiteCode = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vNewsByKeywords")]
	public partial class vNewsByKeywords
	{
		
		private string _Title;
		
		private System.Nullable<System.DateTime> _NewsDate;
		
		private string _PicName;
		
		private string _Contents;
		
		private string _Keyword;
		
		private int _Code;
		
		private int _KeywordCode;
		
		private string _ResourceName;
		
		private int _ResourceSiteCode;
		
		public vNewsByKeywords()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(400) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewsDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> NewsDate
		{
			get
			{
				return this._NewsDate;
			}
			set
			{
				if ((this._NewsDate != value))
				{
					this._NewsDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PicName", DbType="NVarChar(200)")]
		public string PicName
		{
			get
			{
				return this._PicName;
			}
			set
			{
				if ((this._PicName != value))
				{
					this._PicName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contents", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Contents
		{
			get
			{
				return this._Contents;
			}
			set
			{
				if ((this._Contents != value))
				{
					this._Contents = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Keyword", DbType="NVarChar(100)")]
		public string Keyword
		{
			get
			{
				return this._Keyword;
			}
			set
			{
				if ((this._Keyword != value))
				{
					this._Keyword = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="Int NOT NULL")]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeywordCode", DbType="Int NOT NULL")]
		public int KeywordCode
		{
			get
			{
				return this._KeywordCode;
			}
			set
			{
				if ((this._KeywordCode != value))
				{
					this._KeywordCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResourceName", DbType="NVarChar(500)")]
		public string ResourceName
		{
			get
			{
				return this._ResourceName;
			}
			set
			{
				if ((this._ResourceName != value))
				{
					this._ResourceName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResourceSiteCode", DbType="Int NOT NULL")]
		public int ResourceSiteCode
		{
			get
			{
				return this._ResourceSiteCode;
			}
			set
			{
				if ((this._ResourceSiteCode != value))
				{
					this._ResourceSiteCode = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vLatestNews")]
	public partial class vLatestNews
	{
		
		private int _Code;
		
		private string _Title;
		
		private string _ResourceName;
		
		private string _PicName;
		
		private string _Contents;
		
		private System.Nullable<System.DateTime> _NewsDate;
		
		private int _ResourceSiteCode;
		
		private int _ResourceSiteCatCode;
		
		private System.Nullable<int> _CatCode;
		
		private string _ImgUrl;
		
		public vLatestNews()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="Int NOT NULL")]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(400) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResourceName", DbType="NVarChar(500)")]
		public string ResourceName
		{
			get
			{
				return this._ResourceName;
			}
			set
			{
				if ((this._ResourceName != value))
				{
					this._ResourceName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PicName", DbType="NVarChar(200)")]
		public string PicName
		{
			get
			{
				return this._PicName;
			}
			set
			{
				if ((this._PicName != value))
				{
					this._PicName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contents", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Contents
		{
			get
			{
				return this._Contents;
			}
			set
			{
				if ((this._Contents != value))
				{
					this._Contents = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewsDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> NewsDate
		{
			get
			{
				return this._NewsDate;
			}
			set
			{
				if ((this._NewsDate != value))
				{
					this._NewsDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResourceSiteCode", DbType="Int NOT NULL")]
		public int ResourceSiteCode
		{
			get
			{
				return this._ResourceSiteCode;
			}
			set
			{
				if ((this._ResourceSiteCode != value))
				{
					this._ResourceSiteCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResourceSiteCatCode", DbType="Int NOT NULL")]
		public int ResourceSiteCatCode
		{
			get
			{
				return this._ResourceSiteCatCode;
			}
			set
			{
				if ((this._ResourceSiteCatCode != value))
				{
					this._ResourceSiteCatCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CatCode", DbType="Int")]
		public System.Nullable<int> CatCode
		{
			get
			{
				return this._CatCode;
			}
			set
			{
				if ((this._CatCode != value))
				{
					this._CatCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImgUrl", DbType="VarChar(500)")]
		public string ImgUrl
		{
			get
			{
				return this._ImgUrl;
			}
			set
			{
				if ((this._ImgUrl != value))
				{
					this._ImgUrl = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vLatestPicNews")]
	public partial class vLatestPicNews
	{
		
		private int _Code;
		
		private string _Title;
		
		private string _ResourceName;
		
		private string _PicName;
		
		private string _Contents;
		
		private string _ImgUrl;
		
		public vLatestPicNews()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="Int NOT NULL")]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(400) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResourceName", DbType="NVarChar(500)")]
		public string ResourceName
		{
			get
			{
				return this._ResourceName;
			}
			set
			{
				if ((this._ResourceName != value))
				{
					this._ResourceName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PicName", DbType="NVarChar(200)")]
		public string PicName
		{
			get
			{
				return this._PicName;
			}
			set
			{
				if ((this._PicName != value))
				{
					this._PicName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contents", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Contents
		{
			get
			{
				return this._Contents;
			}
			set
			{
				if ((this._Contents != value))
				{
					this._Contents = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImgUrl", DbType="VarChar(500)")]
		public string ImgUrl
		{
			get
			{
				return this._ImgUrl;
			}
			set
			{
				if ((this._ImgUrl != value))
				{
					this._ImgUrl = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NewsEmails")]
	public partial class NewsEmail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Code;
		
		private string _Email;
		
		private bool _Active;
		
		private string _ID;
		
		private string _SenderIP;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodeChanging(int value);
    partial void OnCodeChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnActiveChanging(bool value);
    partial void OnActiveChanged();
    partial void OnIDChanging(string value);
    partial void OnIDChanged();
    partial void OnSenderIPChanging(string value);
    partial void OnSenderIPChanged();
    #endregion
		
		public NewsEmail()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit NOT NULL")]
		public bool Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this.OnActiveChanging(value);
					this.SendPropertyChanging();
					this._Active = value;
					this.SendPropertyChanged("Active");
					this.OnActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="VarChar(50)")]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SenderIP", DbType="VarChar(50)")]
		public string SenderIP
		{
			get
			{
				return this._SenderIP;
			}
			set
			{
				if ((this._SenderIP != value))
				{
					this.OnSenderIPChanging(value);
					this.SendPropertyChanging();
					this._SenderIP = value;
					this.SendPropertyChanged("SenderIP");
					this.OnSenderIPChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EmailLists")]
	public partial class EmailLists : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Code;
		
		private System.DateTime _SendDate;
		
		private int _HCSendTypeCode;
		
		private string _PersianDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodeChanging(int value);
    partial void OnCodeChanged();
    partial void OnSendDateChanging(System.DateTime value);
    partial void OnSendDateChanged();
    partial void OnHCSendTypeCodeChanging(int value);
    partial void OnHCSendTypeCodeChanged();
    partial void OnPersianDateChanging(string value);
    partial void OnPersianDateChanged();
    #endregion
		
		public EmailLists()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SendDate", DbType="DateTime NOT NULL")]
		public System.DateTime SendDate
		{
			get
			{
				return this._SendDate;
			}
			set
			{
				if ((this._SendDate != value))
				{
					this.OnSendDateChanging(value);
					this.SendPropertyChanging();
					this._SendDate = value;
					this.SendPropertyChanged("SendDate");
					this.OnSendDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCSendTypeCode", DbType="Int NOT NULL")]
		public int HCSendTypeCode
		{
			get
			{
				return this._HCSendTypeCode;
			}
			set
			{
				if ((this._HCSendTypeCode != value))
				{
					this.OnHCSendTypeCodeChanging(value);
					this.SendPropertyChanging();
					this._HCSendTypeCode = value;
					this.SendPropertyChanged("HCSendTypeCode");
					this.OnHCSendTypeCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersianDate", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string PersianDate
		{
			get
			{
				return this._PersianDate;
			}
			set
			{
				if ((this._PersianDate != value))
				{
					this.OnPersianDateChanging(value);
					this.SendPropertyChanging();
					this._PersianDate = value;
					this.SendPropertyChanged("PersianDate");
					this.OnPersianDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vNewsEmailItems")]
	public partial class vNewsEmailItems
	{
		
		private int _Code;
		
		private string _Title;
		
		private System.Nullable<System.DateTime> _NewsDate;
		
		private System.Nullable<int> _VisitCount;
		
		public vNewsEmailItems()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="Int NOT NULL")]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(400) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewsDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> NewsDate
		{
			get
			{
				return this._NewsDate;
			}
			set
			{
				if ((this._NewsDate != value))
				{
					this._NewsDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VisitCount", DbType="Int")]
		public System.Nullable<int> VisitCount
		{
			get
			{
				return this._VisitCount;
			}
			set
			{
				if ((this._VisitCount != value))
				{
					this._VisitCount = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EmailListSends")]
	public partial class EmailListSends : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Code;
		
		private int _EmailListCode;
		
		private string _Email;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodeChanging(int value);
    partial void OnCodeChanged();
    partial void OnEmailListCodeChanging(int value);
    partial void OnEmailListCodeChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    #endregion
		
		public EmailListSends()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailListCode", DbType="Int NOT NULL")]
		public int EmailListCode
		{
			get
			{
				return this._EmailListCode;
			}
			set
			{
				if ((this._EmailListCode != value))
				{
					this.OnEmailListCodeChanging(value);
					this.SendPropertyChanging();
					this._EmailListCode = value;
					this.SendPropertyChanged("EmailListCode");
					this.OnEmailListCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NewsImages")]
	public partial class NewsImages : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Code;
		
		private int _NewsCode;
		
		private string _ImgUrl;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodeChanging(int value);
    partial void OnCodeChanged();
    partial void OnNewsCodeChanging(int value);
    partial void OnNewsCodeChanged();
    partial void OnImgUrlChanging(string value);
    partial void OnImgUrlChanged();
    #endregion
		
		public NewsImages()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewsCode", DbType="Int NOT NULL")]
		public int NewsCode
		{
			get
			{
				return this._NewsCode;
			}
			set
			{
				if ((this._NewsCode != value))
				{
					this.OnNewsCodeChanging(value);
					this.SendPropertyChanging();
					this._NewsCode = value;
					this.SendPropertyChanged("NewsCode");
					this.OnNewsCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImgUrl", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string ImgUrl
		{
			get
			{
				return this._ImgUrl;
			}
			set
			{
				if ((this._ImgUrl != value))
				{
					this.OnImgUrlChanging(value);
					this.SendPropertyChanging();
					this._ImgUrl = value;
					this.SendPropertyChanged("ImgUrl");
					this.OnImgUrlChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class spGetRelatedNewsFlowsResult
	{
		
		private System.Nullable<int> _NewsFlowCode;
		
		private System.Nullable<int> _KeyCount;
		
		public spGetRelatedNewsFlowsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewsFlowCode", DbType="Int")]
		public System.Nullable<int> NewsFlowCode
		{
			get
			{
				return this._NewsFlowCode;
			}
			set
			{
				if ((this._NewsFlowCode != value))
				{
					this._NewsFlowCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeyCount", DbType="Int")]
		public System.Nullable<int> KeyCount
		{
			get
			{
				return this._KeyCount;
			}
			set
			{
				if ((this._KeyCount != value))
				{
					this._KeyCount = value;
				}
			}
		}
	}
	
	public partial class spGetNewsflowKeywordsResult
	{
		
		private int _NewsCode;
		
		private System.Nullable<int> _KeywordCount;
		
		public spGetNewsflowKeywordsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewsCode", DbType="Int NOT NULL")]
		public int NewsCode
		{
			get
			{
				return this._NewsCode;
			}
			set
			{
				if ((this._NewsCode != value))
				{
					this._NewsCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeywordCount", DbType="Int")]
		public System.Nullable<int> KeywordCount
		{
			get
			{
				return this._KeywordCount;
			}
			set
			{
				if ((this._KeywordCount != value))
				{
					this._KeywordCount = value;
				}
			}
		}
	}
	
	public partial class spSearchNewsResult
	{
		
		private int _Code;
		
		private string _Title;
		
		private string _ResourceName;
		
		private string _PicName;
		
		private string _Contents;
		
		private System.Nullable<System.DateTime> _NewsDate;
		
		private int _ResourceSiteCode;
		
		private int _ResourceSiteCatCode;
		
		public spSearchNewsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="Int NOT NULL")]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(400) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResourceName", DbType="NVarChar(500)")]
		public string ResourceName
		{
			get
			{
				return this._ResourceName;
			}
			set
			{
				if ((this._ResourceName != value))
				{
					this._ResourceName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PicName", DbType="NVarChar(200)")]
		public string PicName
		{
			get
			{
				return this._PicName;
			}
			set
			{
				if ((this._PicName != value))
				{
					this._PicName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contents", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Contents
		{
			get
			{
				return this._Contents;
			}
			set
			{
				if ((this._Contents != value))
				{
					this._Contents = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewsDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> NewsDate
		{
			get
			{
				return this._NewsDate;
			}
			set
			{
				if ((this._NewsDate != value))
				{
					this._NewsDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResourceSiteCode", DbType="Int NOT NULL")]
		public int ResourceSiteCode
		{
			get
			{
				return this._ResourceSiteCode;
			}
			set
			{
				if ((this._ResourceSiteCode != value))
				{
					this._ResourceSiteCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResourceSiteCatCode", DbType="Int NOT NULL")]
		public int ResourceSiteCatCode
		{
			get
			{
				return this._ResourceSiteCatCode;
			}
			set
			{
				if ((this._ResourceSiteCatCode != value))
				{
					this._ResourceSiteCatCode = value;
				}
			}
		}
	}
	
	public partial class spGetNotSentNewsEmailsResult
	{
		
		private int _Code;
		
		private string _Email;
		
		private bool _Active;
		
		private string _ID;
		
		public spGetNotSentNewsEmailsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="Int NOT NULL")]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit NOT NULL")]
		public bool Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this._Active = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="VarChar(50)")]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
